### ISSUE TITLE
4.3.5 - prep overview

### ISSUE THREAD

**Issue by FrutyX** [DinoDevs/GladiatusCrazyAddon#281]
_(Last checked: 1.1.2022)_

<h3>High priority</h3>

None.

<h3>Medium priority</h3>

None.

<h3>Low priority</h3>

None.

<h3>FINISHED</h3>

- [ ] <strike>Gold statistics rework after Gladiatus updated it's gold counter (#248) </strike> 
 _Current status:_ **TESTING FIX - NOT INCLUDED IN THIS VERSION**
- [x] <strike>Some settings are dependant on other settings (example: #279)</strike>
_Current status:_  **PATCHED** 
- [x] <strike>Audio system rework (#278)</strike>
_Current status:_ **IMPLEMENTED** 

- [x] <strike>Importing settings via notes does not import language + add lang locales (#268 )</strike> 
_Current status:_ **FIXED** 

- [x] <strike>Auction sorting:  2 and 3 digits does not work together well ( #235)</strike>
 _Current status:_ **FIXED** 

- [x] <strike>Gold&XP Icon placement (#257)</strike>
_Current status:_ **FIXED**

**Comment by FrutyX** [comment]
Sorry Gram, I know you are moving, but 2:0 for Apo! 😛

**Comment by GramThanos** [comment]
This week I am in Spain for work. :P Though there sill some packaging 📦 left to be done back in Greece.

**Comment by FrutyX** [comment]
Wish I could help with that damn import/export notes problem (language), but that script is waaaaaaay too complicated for me.

No rush tho, enjoy Spain, try some local food :).

**Comment by GreatApo** [comment]
> Wish I could help with that damn import/export notes problem (language), but that script is waaaaaaay too complicated for me.
> 
> No rush tho, enjoy Spain, try some local food :).

**Comment by FrutyX** [comment]
![dog-surprised](https://user-images.githubusercontent.com/23278552/140186653-9cb17eb8-b53d-4186-b4c9-7fd6e195d7c1.gif)

**Comment by FrutyX** [comment]
Changed #248 from TESTING to FIXED ,-).

**Comment by FrutyX** [comment]
I don't usually don't dig into personal things, but curiosity is my weakness (will probably kill me one day)...

After seeing your Linkedin profiles, shit, it does make sense that you don't have time for some dead browser game, lmao.

And, I have to ask, u guys are brothers? By any chance? I could not resist.

**Comment by GreatApo** [comment]
Yeah, we are twins :P

Thanos takes care of the release the last couple of years. Normally, we would have push for a release because as you said, there are too many features/fixes. However, as he mentioned he is into a transition period now and he is mostly offline :)

**Comment by FrutyX** [comment]
Twins, yeeeeey :D.

And ye, that's fine, I've just picked the wrong time to be active here, when you are using something daily, you clearly want to improve it, despite we all know in what state Gladiatus is, and it's future, it does not mean we should just give up and throw it into a trashcan.

**Comment by FrutyX** [comment]
Changed (again) #248 to PROBLEMATIC (more details in it's issue).

![rough-day-keyboard](https://user-images.githubusercontent.com/23278552/141598488-909815c1-dd7c-43d6-95c9-5110538d137b.gif)

**Comment by FrutyX** [comment]
Issue reworked, list reworked, list updated, removed all my other talk, so it is more clear.

**Comment by FrutyX** [comment]
@GramThanos Hey man, I very appreciate the invitation and I did accept it, but I have to mention, don't have that big expectations, I'll gladly help with anything I can, but my knowledge is basic, and I have more experience with running a website, that doing mostly javascript, to shorten it, if I can do it, I'll do it, if I can't do it, I'll just sit like a duck.

Thank you.

**Comment by GramThanos** [comment]
@FrutyX no problem man, I invited you because you are already helping.

**Comment by FrutyX** [comment]
I've moved the Audio system reworked to **Medium priority**, because I was looking at it, and it's even more broken than I thought, for whatever reason I didn't even make it to work as it at least should.

I am too scared to touch it, Gram has to ready his delete button.

**Comment by FrutyX** [comment]
@GramThanos, @GreatApo 

Don't worry about the stuff I do directly master, just something I am preparing, for the documentation stuff.

**Comment by FrutyX** [comment]
So, I gotta ask guys, can we add the <a href="https://github.com/DinoDevs/GladiatusCrazyAddon/blob/master/documentation/Troubleshooting.md">Troubleshooting guide</a> to the main GitHub page and to this:

![image](https://user-images.githubusercontent.com/23278552/147004881-4dd67e7b-f462-4bb3-a925-b45f8021bc9f.png)

I mean, I can add it, but I better ask if you agree with it, don't want to overdo my permissions.

Also I have zero feedback on the guide itself, so if you dislike something... just name it.

**Comment by GramThanos** [comment]
@FrutyX awesome. Yes, good idea, if you have time please do add it.

**Comment by FrutyX** [comment]
Talkin' about priorities Gram... there is still #279 and #235 without any progress, you got some catching up for Christmas 😛

**Comment by GramThanos** [comment]
Aaaaaaa, low priority these are ...
Learn you will...
![yoda-star-wars](https://user-images.githubusercontent.com/14858959/147111089-6063f17e-ab02-4482-a2ce-a2224752f3b3.gif)

**Comment by FrutyX** [comment]
Damn, but they are not on the list without a reason.... I gotta find a different developer 😄.

Hmmm, Apooooooooooo? 🔊

**Comment by GreatApo** [comment]
> Damn, but they are not on the list without a reason.... I gotta find a different developer 😄.
> 
> Hmmm, Apooooooooooo? 🔊

Thanos spend 5 years studying computer science but failed to identify a string/number sorting bug... 

![image](https://user-images.githubusercontent.com/9620510/147127895-686ab379-0de4-4849-9044-bca7237b527f.png)

**Comment by GramThanos** [comment]
The auction sort needs to be merged with the advance packages filtering code as they solve similar issues. It is not so simple.

**Comment by FrutyX** [comment]
Oh yes, this sounds like a good plan, I'm gonna make this a little sport and brother rivalry and GCA will prosper 🤣.

**Comment by GramThanos** [comment]
I am not the one using parseInt without a base...

**Comment by GreatApo** [comment]
> I am not the one using parseInt without a base...

It was an engineering judgement.... you see what I did there? XD

**Comment by FrutyX** [comment]
List updated, better take a look Gram! :D

Well, a few days will be needed to test everything in one package, #248 will need more time for testing too, #279 should probably be addressed too before a release.

And there are some little things like polishing stuff, but we are getting very close to a stable release.

**Comment by GreatApo** [comment]
We probably need to make a release before the new year and the next one next year

**Comment by FrutyX** [comment]
@GramThanos For the custom market labels, the value label is not translated, I probably can add it to the code, but I was thinking, maybe you can get it directly from the game? Every item has a value, and I remember you did that with Threat in a different issue.

![value](https://user-images.githubusercontent.com/23278552/147159086-9b8cc172-ce09-46de-9022-3efc63dc6f9b.PNG)

**Comment by GramThanos** [comment]
This is already there, but needs improvement. I fixed it but in the wrong branch, I will have to move my changes on the correct one.

**Comment by GramThanos** [comment]
Fix pushed 7b3fdc6f45af8aaa06531d5b5eee44b5847f26c5. Check if it works now, this is server dependent.

**Comment by FrutyX** [comment]
Still the same. Maybe it would be easier to just add the locale in the end.

![value](https://user-images.githubusercontent.com/23278552/147203598-a1d1c80a-e1aa-44d0-8e49-c1b5039ff841.PNG)

**Comment by FrutyX** [comment]
"It's Christmas..."

And Apo took it personally:

![Apo](https://user-images.githubusercontent.com/23278552/147334725-f3e752dd-2763-4f34-b09d-ba30d065980a.PNG)

@GramThanos take notes 🤣

**Comment by FrutyX** [comment]
@GreatApo 

![Výstřižek](https://user-images.githubusercontent.com/23278552/147370536-afd9c494-2c29-4d94-84fc-eae0f0a8508d.PNG)

Didn't Skars had a calculator on his website?

**Comment by GreatApo** [comment]
> @GreatApo 
> 
> ![Výstřižek](https://user-images.githubusercontent.com/23278552/147370536-afd9c494-2c29-4d94-84fc-eae0f0a8508d.PNG)
> 
> Didn't Skars had a calculator on his website?

Has he? Don't remember 😂
I am trying to calculate the gold your guild has stolen (because you want me to) by calculating all the gold spend (assuming 30% discount).

**Comment by FrutyX** [comment]
https://gladiatus.gamerz-bg.com/calculator
 Scroll down, check the source code, it's right there, it was pretty reliable if I remember it correctly.

**Comment by FrutyX** [comment]
> (because you want me to) 

Don't act like it's for me, I am kinda surprised you focused on this feature request, originally it came form my guild mate, not from me, but I do agree it would be useful, also you have a good idea for it.

A lot has changed since I made that request, I am not in that guild anymore, what I am trying to say is, that even if you make it possible, I will not be able to test it, but I am not saying you should not make it.

**Comment by GreatApo** [comment]
> > (because you want me to)
> 
> Don't act like it's for me, I am kinda surprised you focused on this feature request, originally it came from my guild mate, not from me, but I do agree it would be useful, also you have a good idea for it.
> 
> A lot has changed since I made that request, I am not in that guild anymore, what I am trying to say is, that even if you make it possible, I will not be able to test it, but I am not saying you should not make it.

We can make it for everyone except that guild... hahaha
I just had a look, I haven't script anything.

**Comment by FrutyX** [comment]
I smell the sweet taste of progress in the air! List updated.

**Comment by FrutyX** [comment]
> The auction sort needs to be merged with the advance packages filtering code as they solve similar issues. It is not so simple.

I've never been actually using the packages filter, but I agree on this.

I see there are some Issues for packages filtering, and I was thinking, would the thing @GreatApo made in #225  also work with the packages filter, with some modifications of course?

**Comment by FrutyX** [comment]
@GreatApo , @GramThanos 

Boys, I have been planning to create a new issue, a talk one. Sometimes I do comment and ask you things in different Issues, and this is not ideal, for example, I've been using this Issue to comment about something, so that's why I would like to create such Issue that will be pinned so it is visible, the idea (template for it) is here:

> TALK - Only GCA related
> 
> Sometimes, you just have a simple question, or you want to suggest something, but it isn't completely up to create a whole new issue, this is the right place to talk about it.
> 
> Rules:
> 
> 1. As the name suggest, only GCA related talk here, Gladiatus topic is still tolerable, nothing else other than that.
> 2. No vulgarity or spam, keep this Issue clean and when you forget to mention something, just edit your previous post.
> 3. If you found a bug or want to make a suggestion for a feature or enhancement, create a New issue.
> 4. If you are having problems with GCA, make sure to read our <a href="https://github.com/DinoDevs/GladiatusCrazyAddon/blob/master/documentation/Troubleshooting.md">Troubleshooting guide</a> first.
> 5. You are free to use emojis and upload images, all in a reasonable amount.
>
>In case of need, more rules might get added. Comments that will not respect these rules will be deleted.

You both good with this?

**Comment by GramThanos** [comment]
I don't have a problem. Alternatively, we can create a Discord server.

**Comment by FrutyX** [comment]
I've been thinking about a Discord server, buuuuuuuuut, I am not sure it will get any popular (we get people on it), like GitHub is our main platform now, so I am not sure if we also get any people on a discord server.

But that's just my opinion, maybe I am wrong.

**Comment by GramThanos** [comment]
I expect 4 people to join.

**Comment by GreatApo** [comment]
Guys, I track the GCA post in the Gladiatus Forum from time to time. Whoever wants to reach us, they can reach us. There is no reason to create more stuff, the player base is extremely small.

**Comment by FrutyX** [comment]
@GreatApo and about the talk issue? That's the thing, I don't want to comment Issues to tell you something, when it's not related to the Issue, and as you see, for now, I use this Issue for it, but when it's done, I will close it.

**Comment by FrutyX** [comment]
2 more days for #248 testing, but there are some bugs, so I don't know if we should fix them before a release. Current feature requests you are working on needs to be finished and polished before a release, so nothing is broken.

It seems like the release is getting further and further postponed. On one hand, you should release, because it's about time, on the other, you shouldn't, because I was wrong, when I thought we'll make it bug/error free, nothing is ever bug free.

**Comment by FrutyX** [comment]
A note I would like to mention.

I don't know how much work is to release a version, I mean, how long does it take for browsers (checking process) to release it on their stores.

We could make smaller updates (hell, even hotfixes) but I guess it's too much work (changing everything on GitHub, changing it in the addon, changing it on your website) ...

**Comment by GreatApo** [comment]
> A note I would like to mention.
> 
> I don't know how much work is to release a version, I mean, how long does it take for browsers (checking process) to release it on their stores.
> 
> We could make smaller updates (hell, even hotfixes) but I guess it's too much work (changing everything on GitHub, changing it in the addon, changing it on your website) ...

Thanos has set everything up so that we can easily create the addon for multiple browsers. One problem is that Chrome has updated their manifest version from 2 to 3 which we need to update. The review time depends on the store. I think chrome is quite fast/automatic and it takes a day (we will see).
Nowadays we don't have huge bugs, everything that we find just needs small fixes. We usually try to release with all the identified bugs fixed.

**Comment by FrutyX** [comment]
Did he just did it? God be with us.

Btw - Happy new year you two :)

**Comment by GramThanos** [comment]
Happy new year!
